# Generated by Django 5.0.12 on 2025-02-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('TipoDeMonstruo', models.CharField(max_length=100)),
                ('FechaDeLanzamiento', models.CharField(max_length=7)),
                ('CiudadNatal', models.CharField(blank=True, max_length=100, null=True)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('MascotaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='Ediciones',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Serie', models.CharField(max_length=100)),
                ('FechaDeLanzamiento', models.CharField(max_length=7)),
                ('TipoDeGeneracion', models.PositiveSmallIntegerField()),
                ('MunecaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.personajes')),
            ],
        ),
        migrations.CreateModel(
            name='Skullectors',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Serie', models.CharField(max_length=100)),
                ('FechaDeLanzamiento', models.CharField(max_length=7)),
                ('Descripcion', models.TextField()),
                ('MunecaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.personajes')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ediciones',
            constraint=models.CheckConstraint(check=models.Q(('TipoDeGeneracion__in', [1, 2, 3])), name='chk_tipo_generacion'),
        ),
    ]
