# Generated by Django 5.0.12 on 2025-03-03 11:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Required. 15 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='username')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='profile picture')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('gender', models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otro', 'Otro')], max_length=10, verbose_name='gender')),
                ('pronouns', models.CharField(blank=True, max_length=50, verbose_name='pronouns')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ediciones',
            name='chk_tipo_generacion',
        ),
        migrations.RenameField(
            model_name='ediciones',
            old_name='TipoDeGeneracion',
            new_name='generacion',
        ),
        migrations.RenameField(
            model_name='ediciones',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ediciones',
            old_name='FechaDeLanzamiento',
            new_name='lanzamiento',
        ),
        migrations.RenameField(
            model_name='ediciones',
            old_name='Serie',
            new_name='serie',
        ),
        migrations.RenameField(
            model_name='mascotas',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='mascotas',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='mascotas',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='personajes',
            old_name='CiudadNatal',
            new_name='ciudadNatal',
        ),
        migrations.RenameField(
            model_name='personajes',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='personajes',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='personajes',
            old_name='FechaDeLanzamiento',
            new_name='lanzamiento',
        ),
        migrations.RenameField(
            model_name='personajes',
            old_name='MascotaId',
            new_name='mascota',
        ),
        migrations.RenameField(
            model_name='skullectors',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='skullectors',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='skullectors',
            old_name='FechaDeLanzamiento',
            new_name='lanzamiento',
        ),
        migrations.RenameField(
            model_name='skullectors',
            old_name='Serie',
            new_name='serie',
        ),
        migrations.RemoveField(
            model_name='ediciones',
            name='MunecaId',
        ),
        migrations.RemoveField(
            model_name='personajes',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='personajes',
            name='TipoDeMonstruo',
        ),
        migrations.RemoveField(
            model_name='skullectors',
            name='MunecaId',
        ),
        migrations.AddField(
            model_name='ediciones',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ediciones',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ediciones',
            name='muneca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ediciones_as_muneca', to='projects.personajes'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='duenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.personajes'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personajes',
            name='colorFav',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='cumpleanios',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='ediciones',
            field=models.ManyToManyField(blank=True, related_name='Personajes', to='projects.ediciones'),
        ),
        migrations.AddField(
            model_name='personajes',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personajes',
            name='frase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='monstruo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personajes',
            name='sexo',
            field=models.TextField(default='Femenino'),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='certificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='inspiracion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='limitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='muneca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.personajes'),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='precioMercado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='precioOriginal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='foto',
            name='edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.ediciones'),
        ),
        migrations.AddField(
            model_name='foto',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.mascotas'),
        ),
        migrations.AddField(
            model_name='foto',
            name='munieca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.personajes'),
        ),
        migrations.AddField(
            model_name='foto',
            name='skullector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.skullectors'),
        ),
        migrations.AddField(
            model_name='ediciones',
            name='foto',
            field=models.ManyToManyField(blank=True, related_name='ediciones', to='projects.foto'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='foto',
            field=models.ManyToManyField(blank=True, related_name='mascotas', to='projects.foto'),
        ),
        migrations.AddField(
            model_name='personajes',
            name='foto',
            field=models.ManyToManyField(blank=True, related_name='personajes', to='projects.foto'),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='foto',
            field=models.ManyToManyField(blank=True, related_name='skullectors', to='projects.foto'),
        ),
        migrations.AddConstraint(
            model_name='ediciones',
            constraint=models.CheckConstraint(check=models.Q(('generacion__in', [1, 2, 3])), name='chk_generacion'),
        ),
        migrations.AddConstraint(
            model_name='personajes',
            constraint=models.CheckConstraint(check=models.Q(('sexo__in', ['Masculino', 'Femenino'])), name='chk_sexo'),
        ),
        migrations.AddField(
            model_name='personajes',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
