# Generated by Django 5.0.12 on 2025-03-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_usuario_foto_remove_ediciones_chk_tipo_generacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ediciones',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='personajes',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='skullectors',
            name='foto',
        ),
    ]
