# Generated by Django 5.0.12 on 2025-02-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_personajes_edicionesid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='EdicionesId',
        ),
        migrations.AddField(
            model_name='personajes',
            name='EdicionesId',
            field=models.ManyToManyField(blank=True, to='projects.ediciones'),
        ),
    ]
