# Generated by Django 5.0.12 on 2025-02-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_personajes_edicionesid_personajes_edicionesid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ediciones',
            name='MunecaId',
        ),
        migrations.AddField(
            model_name='ediciones',
            name='MunecaId',
            field=models.ManyToManyField(blank=True, to='projects.personajes'),
        ),
    ]
