# Generated by Django 5.0.12 on 2025-03-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_ediciones_foto_remove_mascotas_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='ediciones',
        ),
    ]
