# Generated by Django 5.0.12 on 2025-03-03 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_personajes_ediciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotosEdicion', to='projects.ediciones'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotosMascota', to='projects.mascotas'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='munieca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotosPersonaje', to='projects.personajes'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='skullector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotosSkullector', to='projects.skullectors'),
        ),
    ]
