# Generated by Django 5.0.12 on 2025-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_ediciones_munecaid_ediciones_munecaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ediciones',
            name='Foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='Foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='Foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='Foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
