# Generated by Django 5.0.12 on 2025-02-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_ediciones_foto_mascotas_foto_personajes_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ediciones',
            name='Precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='ColorFav',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='FechaCumpleanios',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='Frase',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personajes',
            name='MejoresAmigos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.personajes'),
        ),
        migrations.AddField(
            model_name='personajes',
            name='Sexo',
            field=models.TextField(default='Femenino'),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='Certificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='EdicionLimitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='Inspiracion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='PrecioMercado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skullectors',
            name='PrecioOriginal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ediciones',
            name='Foto',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='EdicionesId',
            field=models.ManyToManyField(blank=True, null=True, to='projects.ediciones'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='Foto',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='skullectors',
            name='Foto',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddConstraint(
            model_name='personajes',
            constraint=models.CheckConstraint(check=models.Q(('Sexo__in', ['Masculino', 'Femenino'])), name='chk_sexo'),
        ),
    ]
