# Generated by Django 5.0.12 on 2025-03-03 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_foto_edicion_alter_foto_mascota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='mascota',
        ),
        migrations.AlterField(
            model_name='ediciones',
            name='muneca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ediciones', to='projects.personajes'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.ediciones'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.mascotas'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='munieca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.personajes'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='skullector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.skullectors'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='duenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='projects.personajes'),
        ),
        migrations.AlterField(
            model_name='skullectors',
            name='muneca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skullectors', to='projects.personajes'),
        ),
    ]
