# Generated by Django 5.0.12 on 2025-02-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_ediciones_precio_personajes_colorfav_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='MejoresAmigos',
        ),
    ]
