# Generated by Django 5.0.12 on 2025-02-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_personajes_mejoresamigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ediciones',
            name='Precio',
        ),
    ]
